// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ipyzyfunttudmxhwumfk

class SupabaseConfig {
  static const String supabaseUrl = 'https://ipyzyfunttudmxhwumfk.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlweXp5ZnVudHR1ZG14aHd1bWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NjI1MDEsImV4cCI6MjA3NzAzODUwMX0.Eq9bMYZe9Ml8rbUJxAYD9x_Mv2CDazN3_xwYF3mP6ZI';
}
